In [4]:
# Importing allowed packages for the assignment. 
import numpy as np
import pandas as pd
from PIL import Image
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cluster import KMeans
# import networkx as nx
import time
import datetime as dt
from scipy.sparse import coo_matrix
from scipy.io import loadmat
import pickle
from sklearn.utils import graph_shortest_path
from sklearn.neighbors import kneighbors_graph
from sklearn.decomposition import PCA
from matplotlib.artist import Artist
from scipy.spatial import distance
from scipy.stats import multivariate_normal as mvn
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn.datasets import make_blobs
from sklearn.svm import OneClassSVM
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
import seaborn as sn
# from xgboost.sklearn import XGBClassifier
from sklearn.metrics import precision_recall_fscore_support
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
#import sklearn.external.joblib as extjoblib
import joblib
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.mixture import GaussianMixture
from sklearn.metrics import confusion_matrix
from matplotlib.artist import Artist
import sys
!{sys.executable} -m pip install xgboost 
!{sys.executable} -m pip install openpyxl 

import xgboost as xgb
from scipy.spatial import distance
from scipy.stats import multivariate_normal as mvn
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import roc_auc_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn.datasets import make_blobs
from sklearn.svm import OneClassSVM
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
import seaborn as sn
from xgboost.sklearn import XGBClassifier
from sklearn.metrics import precision_recall_fscore_support
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import silhouette_score
from sklearn.mixture import GaussianMixture
#import sklearn.external.joblib as extjoblib
import joblib
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from numpy import argmax

Requirement already satisfied: xgboost in /opt/conda/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.9/site-packages (from xgboost) (1.20.3)
Requirement already satisfied: scipy in /opt/conda/lib/python3.9/site-packages (from xgboost) (1.6.3)
Requirement already satisfied: openpyxl in /opt/conda/lib/python3.9/site-packages (3.0.8)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.9/site-packages (from openpyxl) (1.1.0)

In [5]:
xls = pd.ExcelFile('./reliance.xlsx',engine='openpyxl')
df = pd.read_excel(xls, 'Data Sheet', header=None)

In [13]:

comp = df.iloc[0][1]
#Profit and loss
idx_st = np.where(df[0] == 'PROFIT & LOSS')[0][0]
idx_ed = np.where(df[0] == 'Quarters')[0][0]
dfpl = df.iloc[idx_st:idx_ed]
dfpl = dfpl.dropna().T
dfpl.columns = dfpl.iloc[0]
dfpl = dfpl[1:] #take the data less the header row
dfpl['Company'] = comp

#Balance sheet
idx_st = np.where(df[0] == 'BALANCE SHEET')[0][0]
idx_ed = np.where(df[0] == 'CASH FLOW:')[0][0]
dfbl = df.iloc[idx_st:idx_ed]
dfbl = dfbl.dropna().T
dfbl.columns = dfbl.iloc[0]
dfbl = dfbl[1:]

#Cashflow
idx_st = np.where(df[0] == 'CASH FLOW:')[0][0]
idx_ed = np.where(df[0] == 'DERIVED:')[0][0]
dfcf = df.iloc[idx_st:idx_ed] 
dfcf = dfcf.dropna().T
dfcf.columns = dfcf.iloc[0]
dfcf = dfcf[1:]

In [16]:
dfcf.merge(dfbl).merge(dfcf)

,Report Date,Cash from Operating Activity,Cash from Investing Activity,Cash from Financing Activity,Net Cash Flow,PRICE:,Equity Share Capital,Reserves,Borrowings,Other Liabilities,...,Net Block,Capital Work in Progress,Investments,Other Assets,Total,Receivables,Inventory,Cash & Bank,No. of Equity Shares,Face value
0,2012-03-31 00:00:00,24483,-6301,-7590,10592,371.78,2979,166466,92447,65299,...,138814,25363,38596,124418,327191,16939,46692,40731,2978704713,10
1,2013-03-31 00:00:00,36918,-27601,408,9725,382.82,2936,179094,107219,73108,...,133487,49952,42848,136070,362357,9750,54601,50456,2936308755,10
2,2014-03-31 00:00:00,43261,-73070,13713,-16096,461.01,2940,195730,138761,91412,...,141417,91494,60602,135330,428843,9411,56720,37984,2939547231,10
3,2015-03-31 00:00:00,34374,-64706,8444,-21888,409.12,2943,215539,168251,117753,...,156458,166462,76451,105115,504486,5315,53248,12545,2943334138,10
4,2016-03-31 00:00:00,38134,-36186,-3210,-1262,517.7,2948,228600,194714,172735,...,184910,228697,84015,101375,598997,4465,46486,11028,2948021694,10
5,2017-03-31 00:00:00,49550,-66201,8617,-8034,654.25,2959,260746,217475,225622,...,198526,324837,82899,100540,706802,8177,48951,3023,2958924277,10
6,2018-03-31 00:00:00,71459,-68192,-2001,1266,874.41,5922,287569,239843,277939,...,403885,187022,82862,137504,811273,17555,60837,4255,5921826196,10
7,2019-03-31 00:00:00,42346,-94507,55906,3745,1350.45,5926,381184,307714,302806,...,398374,179463,235635,184158,997630,30089,67561,11081,5925868997,10
8,2020-03-31 00:00:00,94877,-72497,-2541,19839,1103.29,6339,442826,355133,358717,...,532658,109106,276767,244484,1163015,19656,73903,30920,6339267510,10
9,2021-03-31 00:00:00,26185,-141610,101902,-13523,2003.1,6445,653884,270648,389088,...,541258,125953,364828,288026,1320065,19014,81672,17397,6762068814,10